/* ============================================================================
   Migración V10:  Cuentas de correo para notificaciones
   App: Portal de Registros (RegistroCodigos)
   Motor: PostgreSQL (Azure Database for PostgreSQL - Flexible Server)
   ----------------------------------------------------------------------------
   IDEMPOTENTE y NO destructivo: se puede ejecutar sobre una base con datos y
   volver a ejecutar sin efecto.
     psql "<cadena-de-conexion>" -f V10_Notificaciones.sql

   Qué es
   ------
   La lista de cuentas de correo que reciben los avisos del portal, mantenida
   desde Configuración → Notificaciones (solo Compras y Administrador).

   Esta migración crea SOLO el almacenamiento y su mantenimiento. El envío de
   los correos todavía no existe: cuando se defina qué evento lo dispara y por
   dónde se manda, esta tabla es la que hay que leer.

   Por qué es una tabla propia y no un catálogo de cat.*
   -----------------------------------------------------
   Los catálogos de `cat.` alimentan listas desplegables de los formularios y
   los endpoints genéricos /api/catalogos/{tipo} los tratan a todos igual. Esto
   no es una lista desplegable de ningún campo: es configuración del sistema,
   con su propia validación (formato de correo) y su propia pantalla. Meterla
   en `cat.` la habría dejado colgando del mantenimiento genérico de Catálogos,
   donde cualquier texto es una opción válida.
   ============================================================================ */

CREATE SCHEMA IF NOT EXISTS dbo;

/* ---------- Tabla ----------
   Correo se guarda SIEMPRE en minúsculas (lo normaliza la API antes de
   insertar) y lleva UNIQUE: es lo que evita el duplicado que solo se
   diferencia por mayúsculas, que en correo no significan nada.

   CreadoPor queda como texto suelto, sin FK a dbo.UsuarioRol: es un dato de
   bitácora y no debe impedir que se borre un usuario más adelante. */
CREATE TABLE IF NOT EXISTS dbo.NotificacionCuenta (
    Id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Correo        VARCHAR(200) NOT NULL,
    CreadoPor     VARCHAR(200) NULL,
    FechaCreacion TIMESTAMP(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT UQ_NotificacionCuenta_Correo UNIQUE (Correo),
    CONSTRAINT CK_NotificacionCuenta_Minuscula CHECK (Correo = lower(Correo)),
    CONSTRAINT CK_NotificacionCuenta_Formato   CHECK (Correo ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]{2,}$')
);

/* Búsqueda por correo (el UNIQUE ya crea el índice; este es para el ORDER BY
   del listado, que es lo único que hace la pantalla). */
CREATE INDEX IF NOT EXISTS IX_NotificacionCuenta_Correo ON dbo.NotificacionCuenta (Correo);

COMMENT ON TABLE  dbo.NotificacionCuenta         IS 'Cuentas de correo que reciben las notificaciones del portal. Se mantiene en Configuración → Notificaciones.';
COMMENT ON COLUMN dbo.NotificacionCuenta.Correo  IS 'Correo en minúsculas. UNIQUE: no se repite ni cambiando mayúsculas.';

/* ---------- Carga inicial (opcional) ----------
   La tabla se crea VACÍA a propósito: no hay un correo que se pueda suponer.
   Para dejar la lista cargada de una vez, descomente y ajuste:

INSERT INTO dbo.NotificacionCuenta (Correo, CreadoPor)
VALUES ('compras@nutricare.co.cr', 'migracion V10')
ON CONFLICT (Correo) DO NOTHING;
*/
