/* ============================================================================
   Migración V2:  Estado (Pendiente/Procesado) + Roles y asignación de usuarios
   App: Portal de Registros (RegistroCodigos + OrdenPedido)
   Motor: PostgreSQL (Azure Database for PostgreSQL - Flexible Server)
   ----------------------------------------------------------------------------
   Este script es IDEMPOTENTE y NO destructivo: se puede ejecutar sobre una
   base de datos que YA tiene datos, sin perderlos.
   Ejecutar DESPUÉS de RegistroCodigos.sql y OrdenPedido.sql:
     psql "<cadena-de-conexion>" -f V2_Estado_Roles.sql

   Contenido:
     1. Columna Estado en dbo.Solicitud y dbo.OrdenPedido (default 'Pendiente')
     2. Vistas actualizadas para incluir Estado
     3. Catálogo de roles (cat.Rol)
     4. Asignación de rol por usuario (dbo.UsuarioRol) — NO es una tabla de
        usuarios; la identidad la maneja Microsoft (SSO). Aquí solo se guarda
        correo -> rol y el último acceso.
     5. Administradores iniciales: lgomez@nutricare.co.cr y desarrollo@nutricare.co.cr
   ============================================================================ */

CREATE SCHEMA IF NOT EXISTS cat;
CREATE SCHEMA IF NOT EXISTS dbo;

/* ---------- 1. Columna Estado ---------- */
ALTER TABLE dbo.Solicitud
    ADD COLUMN IF NOT EXISTS Estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente';
ALTER TABLE dbo.OrdenPedido
    ADD COLUMN IF NOT EXISTS Estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente';

/* Restringir los valores posibles a 'Pendiente' / 'Procesado' */
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_Solicitud_Estado') THEN
        ALTER TABLE dbo.Solicitud
            ADD CONSTRAINT CK_Solicitud_Estado CHECK (Estado IN ('Pendiente','Procesado'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_OrdenPedido_Estado') THEN
        ALTER TABLE dbo.OrdenPedido
            ADD CONSTRAINT CK_OrdenPedido_Estado CHECK (Estado IN ('Pendiente','Procesado'));
    END IF;
END$$;

/* ---------- 2. Vistas actualizadas (incluyen Estado) ---------- */
DROP VIEW IF EXISTS dbo.vSolicitud;
CREATE VIEW dbo.vSolicitud AS
SELECT  s.Id,
        s.Codigo,
        s.Nombre,
        dep.Nombre  AS Departamento,
        lin.Nombre  AS Linea,
        fam.Nombre  AS Familia,
        prov.Nombre AS Proveedor,
        pais.Nombre AS PaisOrigen,
        s.Estado,
        s.FechaCreacion,
        s.CreadoPor
FROM dbo.Solicitud s
JOIN cat.Departamento dep ON dep.Id = s.DepartamentoId
JOIN cat.Linea        lin ON lin.Id = s.LineaId
JOIN cat.Familia      fam ON fam.Id = s.FamiliaId
JOIN cat.Proveedor    prov ON prov.Id = s.ProveedorId
JOIN cat.PaisOrigen   pais ON pais.Id = s.PaisOrigenId;

DROP VIEW IF EXISTS dbo.vOrdenPedido;
CREATE VIEW dbo.vOrdenPedido AS
SELECT o.Id, p.Nombre AS Producto, o.Descripcion, o.Cajas, o.TotalUnidades,
       b.Nombre AS Bodega, pr.Nombre AS Proveedor, o.FechaEntrega,
       o.Estado, o.FechaCreacion, o.CreadoPor
FROM dbo.OrdenPedido o
JOIN cat.OP_Producto  p  ON p.Id = o.ProductoId
LEFT JOIN cat.OP_Bodega    b  ON b.Id = o.BodegaId
JOIN cat.OP_Proveedor pr ON pr.Id = o.ProveedorId;

/* ---------- 3. Catálogo de roles ---------- */
CREATE TABLE IF NOT EXISTS cat.Rol (
    Id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(30) NOT NULL UNIQUE
);
INSERT INTO cat.Rol (Nombre) VALUES ('General')       ON CONFLICT (Nombre) DO NOTHING;
INSERT INTO cat.Rol (Nombre) VALUES ('Compras')       ON CONFLICT (Nombre) DO NOTHING;
INSERT INTO cat.Rol (Nombre) VALUES ('Administrador') ON CONFLICT (Nombre) DO NOTHING;

/* ---------- 4. Asignación de rol por usuario ----------
   NO es una tabla de usuarios: la identidad la administra Microsoft (SSO).
   Aquí solo se registra el correo que inicia sesión, su rol y el último acceso.
   Se llena sola en cada login (rol 'General' por defecto).                     */
CREATE TABLE IF NOT EXISTS dbo.UsuarioRol (
    Id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email         VARCHAR(200) NOT NULL UNIQUE,
    Nombre        VARCHAR(200) NULL,
    RolId         INT NOT NULL,
    UltimoAcceso  TIMESTAMP(0) NULL,
    FechaCreacion TIMESTAMP(0) NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT FK_UsuarioRol_Rol FOREIGN KEY (RolId) REFERENCES cat.Rol(Id)
);

/* ---------- 5. Administradores iniciales ----------
   Si aún no han iniciado sesión, se crean; si ya existen, se elevan a Administrador. */
INSERT INTO dbo.UsuarioRol (Email, Nombre, RolId)
SELECT 'lgomez@nutricare.co.cr', 'lgomez@nutricare.co.cr', r.Id
FROM cat.Rol r WHERE r.Nombre = 'Administrador'
ON CONFLICT (Email) DO UPDATE
    SET RolId = (SELECT Id FROM cat.Rol WHERE Nombre = 'Administrador');

INSERT INTO dbo.UsuarioRol (Email, Nombre, RolId)
SELECT 'desarrollo@nutricare.co.cr', 'desarrollo@nutricare.co.cr', r.Id
FROM cat.Rol r WHERE r.Nombre = 'Administrador'
ON CONFLICT (Email) DO UPDATE
    SET RolId = (SELECT Id FROM cat.Rol WHERE Nombre = 'Administrador');

/* ============================================================================
   FIN. Verificación rápida (opcional):
     SELECT Email, (SELECT Nombre FROM cat.Rol WHERE Id = u.RolId) AS Rol
     FROM dbo.UsuarioRol u ORDER BY UltimoAcceso DESC NULLS LAST;
   ============================================================================ */
