/* ============================================================================
   Migración V4:  Archivo adjunto por registro (Códigos + Órdenes)
   App: Portal de Registros (RegistroCodigos + OrdenPedido)
   Motor: PostgreSQL (Azure Database for PostgreSQL - Flexible Server)
   ----------------------------------------------------------------------------
   IDEMPOTENTE y NO destructivo: se puede ejecutar sobre una base con datos.
   Ejecutar DESPUÉS de RegistroCodigos.sql, OrdenPedido.sql, V2 y V3:
     psql "<cadena-de-conexion>" -f V4_Adjuntos.sql

   Contenido:
     1. Tabla dbo.Adjunto: guarda UN archivo por registro, en base64.
        - Modulo:  'codigos'  -> dbo.Solicitud
                   'ordenes'  -> dbo.OrdenPedido
        - RegistroId: Id del registro/orden dueño del archivo.
        - Contenido: el archivo codificado en base64 (columna TEXT).
        - UNIQUE(Modulo, RegistroId): un solo archivo por registro (se reemplaza).

   NOTA sobre el tamaño:
     El límite de tamaño NO se controla aquí (la columna TEXT admite hasta ~1 GB).
     Se controla en la API y el frontend con la constante MAX_MB (hoy 5 MB).
     Para subir el límite a 10 MB en el futuro: cambiar MAX_MB en
       api/src/index.js  y  frontend/index.html  y volver a desplegar.
     No requiere cambios en esta tabla.
   ============================================================================ */

CREATE SCHEMA IF NOT EXISTS dbo;

/* ---------- 1. Tabla de adjuntos ---------- */
CREATE TABLE IF NOT EXISTS dbo.Adjunto (
    Id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Modulo        VARCHAR(20)  NOT NULL,          -- 'codigos' | 'ordenes'
    RegistroId    INT          NOT NULL,          -- Id en dbo.Solicitud o dbo.OrdenPedido
    NombreArchivo VARCHAR(260) NOT NULL,          -- nombre original del archivo
    TipoMime      VARCHAR(150) NULL,              -- p.ej. application/pdf, image/png
    Tamano        BIGINT       NULL,              -- tamaño en bytes del archivo original
    Contenido     TEXT         NOT NULL,          -- archivo en base64 (sin prefijo data:)
    SubidoPor     VARCHAR(200) NULL,              -- nombre/correo del usuario que subió
    FechaSubida   TIMESTAMP    NOT NULL DEFAULT (now() at time zone 'utc')
);

/* Restringir el módulo a los dos valores válidos (idempotente). */
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE lower(conname) = 'ck_adjunto_modulo') THEN
        ALTER TABLE dbo.Adjunto
            ADD CONSTRAINT CK_Adjunto_Modulo CHECK (Modulo IN ('codigos','ordenes'));
    END IF;
END $$;

/* Un solo archivo por registro: (Modulo, RegistroId) único.
   Permite el UPSERT (ON CONFLICT) que usa la API para reemplazar el archivo. */
CREATE UNIQUE INDEX IF NOT EXISTS UX_Adjunto_Modulo_Registro
    ON dbo.Adjunto (Modulo, RegistroId);

/* Fin V4 */
