/* ============================================================================
   Migración V6:  Catálogos Modelo -> Marca  +  varios adjuntos por registro
   App: Portal de Registros (RegistroCodigos + OrdenPedido)
   Motor: PostgreSQL (Azure Database for PostgreSQL - Flexible Server)
   ----------------------------------------------------------------------------
   IDEMPOTENTE y NO destructivo: se puede ejecutar varias veces sobre una base
   con datos. Ejecutar DESPUÉS de RegistroCodigos.sql, OrdenPedido.sql y V2..V5:
     psql "<cadena-de-conexion>" -f V6_Modelo_Marca_Adjuntos_Multiples.sql

   Contenido:
     1. cat.Modelo  — catálogo simple de modelos.
     2. cat.Marca   — catálogo de marcas DEPENDIENTE del modelo
                      (mismo patrón que cat.Departamento -> cat.Linea).
     3. dbo.Solicitud: nuevas columnas ModeloId y MarcaId con sus llaves foráneas.
     4. Backfill: los valores de texto que ya existen en dbo.Solicitud.Modelo y
        .Marca se cargan a los catálogos y se apuntan las nuevas columnas.
        Las columnas de texto Modelo y Marca NO se eliminan: quedan como
        respaldo histórico. Si más adelante quiere quitarlas, hágalo en otra
        migración, después de verificar los datos.
     5. dbo.Adjunto: se quita el índice único (Modulo, RegistroId) para permitir
        VARIOS archivos por registro y se deja un índice normal para las
        consultas por registro.

   NOTA sobre el backfill de marcas huérfanas:
     cat.Marca exige un modelo. Si algún registro tiene Marca pero no Modelo,
     esa marca se crea bajo el modelo 'Sin modelo' para no perder el dato. Al
     final el script informa cuántos casos hubo (RAISE NOTICE).
   ============================================================================ */

/* ---------- 0. Verificación previa ----------
   Aborta de una vez si la base actual no es la de la aplicación, para no dejar
   tablas a medio crear en una base equivocada. Ejecute psql con
   -v ON_ERROR_STOP=1 para que se detenga aquí. */
DO $$
BEGIN
    IF to_regclass('dbo.Solicitud') IS NULL THEN
        RAISE EXCEPTION
          'V6 detenida: en la base "%" no existe dbo.Solicitud. Conéctese a la base de la aplicación (dbname=RegistroCodigos) y ejecute primero RegistroCodigos.sql, OrdenPedido.sql y V2..V5.',
          current_database();
    END IF;
    IF to_regclass('dbo.Adjunto') IS NULL THEN
        RAISE EXCEPTION
          'V6 detenida: en la base "%" no existe dbo.Adjunto. Ejecute primero V4_Adjuntos.sql.',
          current_database();
    END IF;
    RAISE NOTICE 'V6 -> base verificada: %', current_database();
END $$;

CREATE SCHEMA IF NOT EXISTS cat;
CREATE SCHEMA IF NOT EXISTS dbo;

/* ---------- 1. Catálogo de modelos ---------- */
CREATE TABLE IF NOT EXISTS cat.Modelo (
    Id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(150) NOT NULL UNIQUE,
    Activo BOOLEAN NOT NULL DEFAULT TRUE
);

/* ---------- 2. Catálogo de marcas, dependiente del modelo ---------- */
CREATE TABLE IF NOT EXISTS cat.Marca (
    Id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ModeloId INT NOT NULL,
    Nombre   VARCHAR(150) NOT NULL,
    Activo   BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT FK_Marca_Modelo FOREIGN KEY (ModeloId) REFERENCES cat.Modelo(Id),
    CONSTRAINT UQ_Marca UNIQUE (ModeloId, Nombre)
);

/* ---------- 3. Columnas nuevas en dbo.Solicitud ---------- */
ALTER TABLE dbo.Solicitud ADD COLUMN IF NOT EXISTS ModeloId INT NULL;
ALTER TABLE dbo.Solicitud ADD COLUMN IF NOT EXISTS MarcaId  INT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE lower(conname) = 'fk_solicitud_modelo') THEN
        ALTER TABLE dbo.Solicitud
            ADD CONSTRAINT FK_Solicitud_Modelo FOREIGN KEY (ModeloId) REFERENCES cat.Modelo(Id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE lower(conname) = 'fk_solicitud_marca') THEN
        ALTER TABLE dbo.Solicitud
            ADD CONSTRAINT FK_Solicitud_Marca FOREIGN KEY (MarcaId) REFERENCES cat.Marca(Id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS IX_Solicitud_ModeloId ON dbo.Solicitud (ModeloId);
CREATE INDEX IF NOT EXISTS IX_Solicitud_MarcaId  ON dbo.Solicitud (MarcaId);

/* ---------- 4. Backfill de los valores de texto que ya existen ----------
   Solo actúa sobre los registros cuyo ModeloId/MarcaId todavía está en NULL,
   así que repetir el script no duplica nada ni pisa correcciones manuales. */
DO $$
DECLARE
    v_modelos_nuevos  INT := 0;
    v_marcas_nuevas   INT := 0;
    v_sol_modelo      INT := 0;
    v_sol_marca       INT := 0;
    v_marcas_huerfanas INT := 0;
    v_sin_modelo_id   INT;
BEGIN
    /* 4.1 Modelos: un registro por cada valor de texto distinto (sin espacios sobrantes). */
    WITH nuevos AS (
        INSERT INTO cat.Modelo (Nombre)
        SELECT DISTINCT btrim(s.Modelo)
        FROM dbo.Solicitud s
        WHERE s.Modelo IS NOT NULL AND btrim(s.Modelo) <> ''
          AND NOT EXISTS (SELECT 1 FROM cat.Modelo m WHERE m.Nombre = btrim(s.Modelo))
        ON CONFLICT (Nombre) DO NOTHING
        RETURNING 1
    ) SELECT count(*) INTO v_modelos_nuevos FROM nuevos;

    /* 4.2 ¿Hay marcas sin modelo? Necesitan un modelo contenedor porque
           cat.Marca.ModeloId es NOT NULL. */
    SELECT count(*) INTO v_marcas_huerfanas
    FROM dbo.Solicitud s
    WHERE s.Marca IS NOT NULL AND btrim(s.Marca) <> ''
      AND (s.Modelo IS NULL OR btrim(s.Modelo) = '');

    IF v_marcas_huerfanas > 0 THEN
        INSERT INTO cat.Modelo (Nombre) VALUES ('Sin modelo')
        ON CONFLICT (Nombre) DO NOTHING;
    END IF;
    SELECT Id INTO v_sin_modelo_id FROM cat.Modelo WHERE Nombre = 'Sin modelo';

    /* 4.3 Marcas: cada par (modelo, marca) que aparece en los registros.
           Las marcas sin modelo van bajo 'Sin modelo'. */
    WITH pares AS (
        SELECT DISTINCT
               COALESCE(m.Id, v_sin_modelo_id) AS modelo_id,
               btrim(s.Marca)                  AS marca
        FROM dbo.Solicitud s
        LEFT JOIN cat.Modelo m
               ON m.Nombre = btrim(s.Modelo) AND btrim(COALESCE(s.Modelo,'')) <> ''
        WHERE s.Marca IS NOT NULL AND btrim(s.Marca) <> ''
    ), nuevas AS (
        INSERT INTO cat.Marca (ModeloId, Nombre)
        SELECT p.modelo_id, p.marca
        FROM pares p
        WHERE p.modelo_id IS NOT NULL
        ON CONFLICT (ModeloId, Nombre) DO NOTHING
        RETURNING 1
    ) SELECT count(*) INTO v_marcas_nuevas FROM nuevas;

    /* 4.4 Apuntar las columnas nuevas de los registros. */
    UPDATE dbo.Solicitud s
       SET ModeloId = m.Id
      FROM cat.Modelo m
     WHERE s.ModeloId IS NULL
       AND s.Modelo IS NOT NULL AND btrim(s.Modelo) <> ''
       AND m.Nombre = btrim(s.Modelo);
    v_sol_modelo := 0;
    GET DIAGNOSTICS v_sol_modelo = ROW_COUNT;

    UPDATE dbo.Solicitud s
       SET MarcaId = mar.Id
      FROM cat.Marca mar
     WHERE s.MarcaId IS NULL
       AND s.Marca IS NOT NULL AND btrim(s.Marca) <> ''
       AND mar.Nombre = btrim(s.Marca)
       AND mar.ModeloId = COALESCE(s.ModeloId, v_sin_modelo_id);
    GET DIAGNOSTICS v_sol_marca = ROW_COUNT;

    RAISE NOTICE 'V6 backfill -> modelos creados: %, marcas creadas: %, registros con ModeloId: %, registros con MarcaId: %',
                 v_modelos_nuevos, v_marcas_nuevas, v_sol_modelo, v_sol_marca;
    IF v_marcas_huerfanas > 0 THEN
        RAISE NOTICE 'V6 aviso -> % registro(s) tenían Marca sin Modelo; esas marcas quedaron bajo el modelo "Sin modelo". Revíselos y reasígnelos desde Catálogos.',
                     v_marcas_huerfanas;
    END IF;
END $$;

/* ---------- 5. Varios adjuntos por registro ----------
   Se quita el índice único que limitaba a un archivo por registro (creado en V4)
   y se deja un índice normal, que es lo que necesitan las consultas por registro. */
DROP INDEX IF EXISTS dbo.UX_Adjunto_Modulo_Registro;
CREATE INDEX IF NOT EXISTS IX_Adjunto_Modulo_Registro ON dbo.Adjunto (Modulo, RegistroId);

/* Fin V6 */
