/* ============================================================================
   Migración V8:  Justificación en Solicitud de Orden de Pedido
   ----------------------------------------------------------------------------
   Ejecución (idempotente, se puede correr sobre una base con datos):

     psql "<cadena-de-conexion>" -f V8_Justificacion.sql

   Qué hace:
     1. cat.OP_Justificacion            — catálogo nuevo (lista desplegable
                                          gestionable desde Catálogos y desde el
                                          botón ＋ del formulario).
     2. dbo.OrdenPedido.JustificacionId — columna nueva, NULL, con FK al
                                          catálogo. Queda NULL en las órdenes
                                          que ya existen: el campo es
                                          obligatorio en el formulario, no en la
                                          base, para no invalidar el histórico.
     3. dbo.vOrdenPedido                — se le agrega Justificacion AL FINAL de
                                          la lista de columnas (CREATE OR REPLACE
                                          VIEW en PostgreSQL solo admite agregar
                                          columnas al final, nunca en el medio).

   OJO: el catálogo se crea VACÍO. Como el campo es obligatorio en el
   formulario, nadie podrá guardar una orden nueva hasta que un usuario con rol
   Compras o Administrador agregue al menos una opción (Catálogos →
   Justificación, o el botón ＋ junto al campo). Si ya tiene la lista definida,
   descoméntela al final de este script.
   ============================================================================ */

/* ---------- Verificación previa: que sea la base de la aplicación ---------- */
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables
                   WHERE table_schema='dbo' AND lower(table_name)='ordenpedido') THEN
        RAISE EXCEPTION 'Esta no es la base de RegistroCodigos (no existe dbo.OrdenPedido). Script abortado.';
    END IF;
END $$;

/* ---------- 1. Catálogo ---------- */
CREATE TABLE IF NOT EXISTS cat.OP_Justificacion (
    Id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(300)  NOT NULL UNIQUE,
    Activo BOOLEAN       NOT NULL DEFAULT TRUE
);

/* ---------- 2. Columna en la orden ---------- */
ALTER TABLE dbo.OrdenPedido ADD COLUMN IF NOT EXISTS JustificacionId INT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE lower(conname) = 'fk_op_justificacion') THEN
        ALTER TABLE dbo.OrdenPedido
            ADD CONSTRAINT FK_OP_Justificacion FOREIGN KEY (JustificacionId)
            REFERENCES cat.OP_Justificacion(Id);
    END IF;
END $$;

/* ---------- 3. Vista del listado ---------- */
CREATE OR REPLACE VIEW dbo.vOrdenPedido AS
SELECT o.Id, p.Nombre AS Producto, o.Descripcion, o.Cajas, o.TotalUnidades,
       b.Nombre AS Bodega, pr.Nombre AS Proveedor, o.FechaEntrega,
       o.Estado, o.FechaCreacion, o.CreadoPor,
       ju.Nombre AS Justificacion
FROM dbo.OrdenPedido o
JOIN cat.OP_Producto  p  ON p.Id = o.ProductoId
LEFT JOIN cat.OP_Bodega    b  ON b.Id = o.BodegaId
JOIN cat.OP_Proveedor pr ON pr.Id = o.ProveedorId
LEFT JOIN cat.OP_Justificacion ju ON ju.Id = o.JustificacionId;

/* ---------- 4. Opciones iniciales (opcional) ----------
   Descomente y ajuste la lista. El ON CONFLICT deja el script idempotente.

INSERT INTO cat.OP_Justificacion (Nombre) VALUES
    ('Reposición de inventario'),
    ('Pedido de cliente'),
    ('Faltante de bodega'),
    ('Producto nuevo')
ON CONFLICT (Nombre) DO NOTHING;
*/

DO $$
DECLARE n INT;
BEGIN
    SELECT count(*) INTO n FROM cat.OP_Justificacion;
    RAISE NOTICE 'V8 listo -> cat.OP_Justificacion (% opciones), dbo.OrdenPedido.JustificacionId y dbo.vOrdenPedido actualizados.', n;
    IF n = 0 THEN
        RAISE NOTICE 'ATENCION: el catalogo quedo vacio. Agregue al menos una opcion en Catalogos -> Justificacion, o no se podran guardar ordenes nuevas.';
    END IF;
END $$;
